# Generated by Django 4.2.6 on 2023-11-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='openRate',
            field=models.BooleanField(default=False),
        ),
    ]
