# Generated by Django 4.2.6 on 2023-12-02 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0002_pitch_openrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitch',
            old_name='openRate',
            new_name='open_rate',
        ),
    ]
