# Generated by Django 4.2.6 on 2023-11-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
