# Generated by Django 4.2.6 on 2023-11-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_meeting'),
        ('meetings', '0003_alter_meeting_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='comments',
            field=models.ManyToManyField(to='comments.comment'),
        ),
    ]
