# Generated by Django 4.2.6 on 2023-11-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meeting_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='video',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
