# Generated by Django 4.2.6 on 2023-12-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_meeting'),
        ('meetings', '0006_alter_meeting_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='comments',
            field=models.ManyToManyField(blank=True, to='comments.comment'),
        ),
    ]
