# Generated by Django 4.2.6 on 2023-11-30 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pitches', '0002_pitch_openrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('criteria', '0001_initial'),
        ('meetings', '0005_meeting_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criteria.criteria')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitches.pitch')),
            ],
        ),
    ]
